### ISSUE TITLE
as Service

### ISSUE THREAD

**Issue by sr2ds** [alitarfa/coin-miner-android-library#1]
Hello Bro,

Did you succeed in doing this implementation in background as a Service?

I am doing this but I have not yet succeeded because for some reason the coinhive script does not work in the transparent webview of the service.

**Comment by alitarfa** [comment]
hi friend, I have just done for webview in the active layout, not for the service background , if you want i will do it for you but it takes some time because I have some work this moment

**Comment by sr2ds** [comment]
I'm trying to implement this a week, but my knowledge in Java is somewhat limited.

I even managed to make a transparent webview work as a service, a get / post for example, running, however, the cogeneration service itself does not run. I did not understand the reason for this

Even consider in learning how to develop the Java miner for an xmr pool, but it would take even longer.

I will follow your process and try to implement something from what you have already done, I believe you take much longer than you do not understand almost anything, but what you started is already amazing!

**Comment by alitarfa** [comment]
so , you must know about service in Android is not simple to do because  google limited some working service in the backgound 
for less one service run int the background you have  two method 
1- foreground service (make a small search )
2- by the JobScheduler( make a small search) 
and for me, the library run without any problem and I have presented in a workshop of my univ

**Comment by sr2ds** [comment]
Foreground service would be the background feature, right?
When the application is open, however, minimized.
This way I managed to do but I need to make this run when the application
terminates.
However, I did too. But specifically the coinhive does not work, understand?
I even got a setinterval with an http call running forever, even with the
app closed.

**Comment by sr2ds** [comment]
The problem specifically is that even running the webview as a service, the
coinhive does not work. Understood?
But this is because I do not know how to do a very effective debugging to
understand the reason for not running.
